src/Entity/ClubData.php
<?php
namespace App\Entity;

use Exception;

class ClubData
{
    private $club;
    private $goals;
    private $goalsAchieved;
    private $goalsAchievedNumber;
    private $goalsNotAchieved;

    public function __call($name, $params) {
        if ($this->club instanceof Club) {
            $method = 'get'.ucfirst($name);
            if (method_exists($this->club, $method)) {
                return $this->club->{$method}();
            }
        }
        throw new Exception('Method "Club::' . $method . '()" does not exists!');
    }

    public function getClub() {
        return $this->club;
    }
    public function setClub($club) {
        $this->club = $club;
    }
    public function getGoals() {
        return $this->goals;
    }
    public function setGoals($goals) {
        $this->goals = $goals;
    }
    public function getGoalsNumber() {
        return count($this->goals);
    }
    public function getGoalsAchieved() {
        return $this->goalsAchieved;
    }
    public function setGoalsAchieved($goalsAchieved) {
        $this->goalsAchieved = $goalsAchieved;
    }
    public function getGoalsAchievedNumber() {
        return $this->goalsAchievedNumber;
    }
    public function setGoalsAchievedNumber($goalsAchievedNumber) {
        $this->goalsAchievedNumber = $goalsAchievedNumber;
    }
    public function getGoalsNotAchieved() {
        return $this->goalsNotAchieved;
    }
    public function setGoalsNotAchieved($goalsNotAchieved) {
        $this->goalsNotAchieved = $goalsNotAchieved;
    }
}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Strona główna{% endblock %}

{% block body %}

	<div class="container">
		{% for flashError in app.flashes('note') %}
			<div class="alert alert-warning mt-3" role="alert">{{ flashError }}</div>
		{% endfor %}
		{% for flashSuccess in app.flashes('success') %}
			<div class="alert alert-success mt-3" role="alert">{{ flashSuccess }}</div>
		{% endfor %}

		<div class="row">
			<div class="col">
				<h2 class="mt-3">Strona główna</h2>

                {% if clubs is not empty %}
				<h5 class="mt-3">Twoje kluby</h5>
				<ul class="list-group mt-4">
					{% for club in clubs %}
                        {% if club.goalsNotAchieved|length > 0 %}
                            <li class="list-group-item {% if club.goalsNotAchieved|length <= 0 %}text-muted{% endif %}">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mt-1">
                                        {% if club.isOwner %}<span class="text-primary"><i class="bi bi-star-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Jesteś właścicielem"></i></span>{% endif %}
                                        {{ club.name }}
                                        {% if not club.isPublic %}<span class="text-danger"><i class="bi bi-lock-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Klub prywatny"></i></span>{% endif %}
                                    </h5>
                                </div>
                                <div class="d-flex w-100 justify-content-between border-top pt-1">
                                    <p>Cele: <span class="badge bg-success">{{ club.goalsAchievedNumber }}</span>/<span class="badge bg-danger">{{ club.goalsNumber }}</span></p>
                                    <div>
                                        <a href="{{ path('club_show', {id : club.id}) }}" class="btn btn-primary btn-sm">Wejdź</a>
                                        <button {% if club.goalsNotAchieved|length <= 0 %}disabled class="btn btn-outline-secondary btn-sm"{% else %}class="btn btn-outline-primary btn-sm"{% endif %} type="button" data-bs-toggle="collapse" data-bs-target="#clubCollapse{{ club.id }}" aria-expanded="false" aria-controls="collapseExample">
                                            Rozwiń
                                        </button>
                                    </div>
                                </div>

                                <div class="collapse {% if club.goalsNotAchieved|length <= 3 %}show{% endif %}" id="clubCollapse{{ club.id }}">
                                    <ul class="list-group mt-1">
                                        {% for goal in club.goalsNotAchieved %}
                                            <li class="list-group-item">
                                                <div class="row">
                                                    <div class="col-auto">
                                                        <i class="{{ goal.iconClassName | default("bi-star")  }}"></i>
                                                    </div>
                                                    <div class="col">
                                                            {{ goal.name }}
                                                    </div>
                                                    <div class="col-12 col-md-auto">
                                                        {% if goal.isAchieved %}
                                                            <button disabled class="btn btn-sm btn-primary w-100">Wykonane</button>
                                                        {% elseif goal.isAchieved is null %}
                                                            <button disabled class="btn btn-sm btn-dark">Status nieznany, odśwież stronę</button>
                                                        {% else %}
                                                            <a class="btn btn-sm btn-success w-100" href="{{ path('goal_achieve', { id: goal.id }) }}">Wykonaj</a>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </li>
                        {% endif %}
					{% endfor %}
				</ul>

				<h5 class="mt-3">Kluby zakończone</h5>
                <p class="text-muted">Kluby w których ukończyłeś wszystkie cele</p>
				<ul class="list-group mt-4">
					{% for club in clubs %}
                        {% if club.goalsNotAchieved|length <= 0 %}
                            <li class="list-group-item text-muted">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mt-1">
                                        {% if club.isOwner %}<span class="text-primary"><i class="bi bi-star-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Jesteś właścicielem"></i></span>{% endif %}
                                        {{ club.name }}
                                        {% if not club.isPublic %}<span class="text-danger"><i class="bi bi-lock-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Klub prywatny"></i></span>{% endif %}
                                    </h5>
                                </div>
                                <div class="d-flex w-100 justify-content-between border-top pt-1">
                                    <p>Cele: <span class="badge bg-success">{{ club.goalsAchievedNumber }}</span>/<span class="badge bg-danger">{{ club.goalsNumber }}</span></p>
                                    <div>
                                        <a href="{{ path('club_show', {id : club.id}) }}" class="btn btn-primary btn-sm">Wejdź</a>
                                        <button {% if club.goalsNotAchieved|length <= 0 %}disabled class="btn btn-outline-secondary btn-sm"{% else %}class="btn btn-outline-primary btn-sm"{% endif %} type="button" data-bs-toggle="collapse" data-bs-target="#clubCollapse{{ club.id }}" aria-expanded="false" aria-controls="collapseExample">
                                            Rozwiń
                                        </button>
                                    </div>
                                </div>

                                <div class="collapse {% if club.goalsNotAchieved|length <= 3 %}show{% endif %}" id="clubCollapse{{ club.id }}">
                                    <ul class="list-group mt-1">
                                        {% for goal in club.goalsNotAchieved %}
                                            <li class="list-group-item">
                                                <div class="row">
                                                    <div class="col-auto">
                                                        <i class="{{ goal.iconClassName | default("bi-star")  }}"></i>
                                                    </div>
                                                    <div class="col">
                                                            {{ goal.name }}
                                                    </div>
                                                    <div class="col-12 col-md-auto">
                                                        {% if goal.isAchieved %}
                                                            <button disabled class="btn btn-sm btn-primary w-100">Wykonane</button>
                                                        {% elseif goal.isAchieved is null %}
                                                            <button disabled class="btn btn-sm btn-dark">Status nieznany, odśwież stronę</button>
                                                        {% else %}
                                                            <a class="btn btn-sm btn-success w-100" href="{{ path('goal_achieve', { id: goal.id }) }}">Wykonaj</a>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </li>
                        {% endif %}
					{% endfor %}
				</ul>
                {% else %}
                    <p class="text-muted">
                        Nie należysz jeszcze do żadnego klubu.
                        <br/><a href="{{ path('clubs') }}">Dołącz do klubu</a> lub <a href="{{ path('club_create') }}">załóż nowy</a>.
                    </p>
                {% endif %}
			</div>
			{# <div class="col-12 col-lg-3">
				<div class="card mt-4">
					<div class="card-body">
						<h5 class="card-title">Posiadasz kod?</h5>
						<p class="card-text">Jeśli dostałeś kod dostępu od właściciela prywatnego klubu wpisz go poniżej aby dołączyć:</p>
					</div>
				</div>
			</div> #}
		</div>
	</div>
{% endblock %}